name: Build and deploy ASP.NET Core app to Azure Web App - ClipNChic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Đảm bảo đúng version bạn đang dùng

      - name: Restore dependencies
        run: dotnet restore ClipNchic.Api/ClipNchic.Api.csproj

      - name: Build project
        run: dotnet build ClipNchic.Api/ClipNchic.Api.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ClipNchic.Api/ClipNchic.Api.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EA38CAE8B1EF40289C1C570284647F9C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6AA165BFD29E4822B6C2712BC2BF4D1B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_12FC1E95826D4B72888C8D729628F328 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ClipNChic'
          slot-name: 'Production'
          package: ./app